name: Metrics

on:
  schedule: # 00:00 EST == 05:00 UTC
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: lowlighter/metrics@latest
      with:
        user: ${{ github.repository_owner }}
        filename: profile/metrics.svg
        token: ${{ secrets.GITHUB_TOKEN }}
        base: header, activity, community, repositories, metadata
        plugin_activity: no
        plugin_followup: yes
        plugin_followup_sections: repositories
        plugin_habits: yes
        plugin_habits_facts: yes
        plugin_habits_charts: no
